# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='exame_medico',
        ),
        migrations.AddField(
            model_name='employees',
            name='exame_medico_demissional',
            field=models.DateField(blank=True, help_text='Data do exame demissional', null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='data_carteira',
            field=models.DateField(help_text='Data da carteira'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='exame_admissional',
            field=models.DateField(blank=True, help_text='Data do exame admissional', null=True),
        ),
    ]
